#!/bin/sh

HELP_MSG="Tusker : A dead simple todo manager

    Add a new task        : tusker add TASK_DESCRIPTION
    Mark a task as done   : tusker check TASK_ID
    Mark a task as undone : tusker uncheck TASK_ID
    Delete a task         : tusker del TASK_ID
    Show existing tasks   : tusker show
"

FILE_DIR="$HOME/.cache/tusker"
FILE_NAME="$FILE_DIR/tasks.txt"
TICK='✓ '
CROSS='❌ '
DELIM='$$$'

check_args() {
    if [ $# -eq 1 ] && ([ "$1" = "show" ] || [ "$1" = "help" ]); then
        return
    fi

    if [ $# -gt 1 ] && [ "$1" = "add" ]; then
        return
    fi

    if [ $# -ne 2 ]; then
        printf "Not a valid command. Type 'tusker help' for usage.\n"
        exit
    fi
}

create_file() {
    mkdir -p "$FILE_DIR"
    if [ ! -e "$FILE_NAME" ]; then
        touch "$FILE_NAME"
    fi
}

add_task() {
    task_desc="$1"
    current_timestamp=$(date +"%d %B %Y %H:%M:%S")
    task_string="$CROSS $DELIM   $task_desc $DELIM  $current_timestamp"

    printf "%b\n" "$task_string" >> "$FILE_NAME"
}

delete_task() {
    task_id=$1
    sed -i -e "$task_id""d" "$FILE_NAME"
}

check_task() {
    task_id=$1
    sed -i "$task_id s/^./$TICK/" "$FILE_NAME"
}

uncheck_task() {
    task_id=$1
    sed -i "$task_id s/^./$CROSS/" "$FILE_NAME"
}

show_tasks() {
    line_count=$(wc -l $FILE_NAME | awk '{print $1}')

    if [ $line_count -eq 0 ]; then
        printf "You're all caught up!!\n"
        return
    fi

    nl "$FILE_NAME" | column -t -s $DELIM
}


main() { 
    check_args "$@"
    create_file

    action=$1
    
    case $action in 
        add)
        shift
        add_task "$*"
        printf "Task added\n"
        ;;
    
        del)
        delete_task "$2"
        printf "Task deleted\n"
        ;;
    
        check)
        check_task "$2"
        printf "Task marked as done\n"
        ;;

        uncheck)
        uncheck_task "$2"
        printf "Task marked as undone\n"
        ;;
    
        show)
        show_tasks
        ;;

        help)
        printf "%s" "$HELP_MSG"
        ;;
        
        *)
        printf "Not a valid command. Type 'tusker help' for usage.\n"
        ;;

    esac
}

main "$@"
