#!/bin/sh

# Author : Deep Bhattacharyya (https://github.com/coderick14)

HELP_MSG="
 _             _             
 | |_ _   _ ___| | _____ _ __ 
 | __| | | / __| |/ / _ \ '__|
 | |_| |_| \__ \   <  __/ |   
  \__|\__,_|___/_|\_\___|_|   

  A dead simple todo manager

    Add a new task        : tusker add TASK_DESCRIPTION
    Mark a task as done   : tusker check TASK_ID
    Mark a task as undone : tusker uncheck TASK_ID
    Delete a task         : tusker del TASK_ID
    Edit task description : tusker edit TASK_ID NEW_TASK_DESCRIPTION
    Show existing tasks   : tusker show
"

FILE_DIR="$HOME/.cache/tusker"
FILE_NAME="$FILE_DIR/tasks.txt"
TICK='✓ '
CROSS='❌ '
DELIM='$$$'

check_args() {
    if [ $# -eq 1 ] && ([ "$1" = "show" ] || [ "$1" = "help" ]); then
        return
    fi

    if [ $# -gt 1 ]; then
        return
    else
        printf "Not a valid command. Type 'tusker help' for usage.\n"
        exit
    fi
}

create_file() {
    mkdir -p "$FILE_DIR"
    if [ ! -e "$FILE_NAME" ]; then
        touch "$FILE_NAME"
    fi
}

add_task() {
    task_desc="$1"
    current_timestamp=$(date +"%d %B %Y %H:%M:%S")
    task_string="$CROSS $DELIM   $task_desc $DELIM  $current_timestamp"

    printf "%b\n" "$task_string" >> "$FILE_NAME"
}

delete_task() {
    format_str=""
    for task_id in "$@"
    do
        format_str="$task_id""d;""$format_str"
    done
    sed -i -e "$format_str" "$FILE_NAME"
}

check_task() {
    for task_id in "$@"
    do
        sed -i "$task_id s/^./$TICK/" "$FILE_NAME"
    done
}

uncheck_task() {
    for task_id in "$@"
    do
        sed -i "$task_id s/^./$CROSS/" "$FILE_NAME"
    done
}

edit_task() {
    task_id="$1"
    shift
    task_desc="$*"
    current_timestamp=$(date +"%d %B %Y %H:%M:%S")
    task_string="$CROSS $DELIM   $task_desc $DELIM  $current_timestamp"
    sed -i "$task_id s/.*/$task_string/" "$FILE_NAME"
}

show_tasks() {
    line_count=$(wc -l $FILE_NAME | awk '{print $1}')

    if [ $line_count -eq 0 ]; then
        printf "You're all caught up!!\n"
        return
    fi

    nl "$FILE_NAME" | column -t -s $DELIM
}


main() { 
    check_args "$@"
    create_file

    action=$1
    
    case $action in 
        add)
        shift
        add_task "$*"
        printf "Task added\n"
    
        ;;
        del)
        shift
        delete_task "$@"
        printf "Task(s) deleted\n"
        ;;
    
        check)
        shift
        check_task "$@"
        printf "Task(s) marked as done\n"
        ;;

        uncheck)
        shift
        uncheck_task "$@"
        printf "Task(s) marked as undone\n"
        ;;
    
        edit)
        shift
        edit_task "$@"
        printf "Task edited\n"
        ;;

        show)
        show_tasks
        ;;

        help)
        printf "%s" "$HELP_MSG"
        ;;
        
        *)
        printf "Not a valid command. Type 'tusker help' for usage.\n"
        ;;

    esac
}

main "$@"
